# GitHub Pages Jekyll 配置
title: Kalendar - Android Calendar App
description: AI-powered quality analysis for Android calendar application
url: "https://sagarey.github.io"
baseurl: "/kalendar"

# Markdown 设置
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 插件
plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-feed

# 主题设置
remote_theme: pages-themes/minimal@v0.2.0

# 包含的文件
include:
  - "*.md"
  - "*.html" 
  - "*.png"
  - "*.xml"

# 排除的文件
exclude:
  - .git/
  - .github/
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - "*.sh"

# 默认设置
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "*.md"
    values:
      layout: "default"
