name: Holiday Generator

on:
  schedule:
    # Run every year on 1st December, midnight
    - cron: "0 0 1 12 *"
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/holiday-generator/package-lock.json"
      - ".github/workflows/holiday-generator/config.js"

jobs:
  generate:
    name: Generate ICS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - name: Install NodeJS
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
        with:
          node-version: 20
      - name: Run script
        env:
          LOG_ENABLED: true
        working-directory: ./.github/workflows/holiday-generator
        run: "npm install && npm start"

      - id: app-token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create PR
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          token: ${{ steps.app-token.outputs.token }}
          sign-commits: true
          branch: fossifybot/holidays
          commit-message: "chore: update holidays"
          title: "chore: update holidays"
          body: " "
